-- INDEXATION PROXY: a URL with GSC impressions is indexed. Zero impressions
-- ever = either not indexed, or indexed with no demand — the next column tells
-- you which, because a page Google has never shown cannot accumulate a position.
WITH published(url) AS (VALUES
  ('https://triaperformance.com/blog/carga-entrenamiento-amateur-metricas-elite/'),
  ('https://triaperformance.com/blog/caso-de-estudio-progresion-ftp-ciclismo-master/'),
  ('https://triaperformance.com/blog/ciclismo-perdida-de-peso-sostenible/'),
  ('https://triaperformance.com/blog/como-ajustar-entrenamiento-fatiga-triatlon/'),
  ('https://triaperformance.com/blog/como-calcular-ftp-ciclismo/'),
  ('https://triaperformance.com/blog/como-elegir-tu-plan-de-maraton/'),
  ('https://triaperformance.com/blog/como-entrenar-primera-maraton-volumen/'),
  ('https://triaperformance.com/blog/como-entrenar-series-de-umbral-potencia-rpe/'),
  ('https://triaperformance.com/blog/como-programar-transiciones-carrera-hyrox-sleds/'),
  ('https://triaperformance.com/blog/correr-para-bajar-de-peso-kilometraje/'),
  ('https://triaperformance.com/blog/distribucion-carga-triatlon-larga-distancia/'),
  ('https://triaperformance.com/blog/dolor-tendon-de-aquiles/'),
  ('https://triaperformance.com/blog/durabilidad-maraton-evitar-muro/'),
  ('https://triaperformance.com/blog/durabilidad-muscular-maraton-entrenamiento/'),
  ('https://triaperformance.com/blog/ejercicios-core-ciclistas-dolor-lumbar/'),
  ('https://triaperformance.com/blog/entrenamiento-hibrido-perdida-peso-hyrox/'),
  ('https://triaperformance.com/blog/entrenamiento-sistema-digestivo-triatlon/'),
  ('https://triaperformance.com/blog/entrenar-el-umbral-sin-tiras-de-lactato/'),
  ('https://triaperformance.com/blog/estructurar-volumen-plan-entrenamiento-maraton/'),
  ('https://triaperformance.com/blog/fuerza-running-kettlebell/'),
  ('https://triaperformance.com/blog/guia-pacing-maraton-valencia/'),
  ('https://triaperformance.com/blog/index/'),
  ('https://triaperformance.com/blog/metodo-noruego-ciclismo-entrenamiento-umbral/'),
  ('https://triaperformance.com/blog/metodo-noruego-entrenamiento-running-autoregulacion/'),
  ('https://triaperformance.com/blog/metodo-noruego-umbral-running-rpe/'),
  ('https://triaperformance.com/blog/mito-ftp-estatico-ciclismo/'),
  ('https://triaperformance.com/blog/nutricion-triatlon-larga-distancia-120g/'),
  ('https://triaperformance.com/blog/pacing-triatlon-larga-distancia-ironman/'),
  ('https://triaperformance.com/blog/pasar-de-media-distancia-a-ironman-entrenamiento/'),
  ('https://triaperformance.com/blog/plan-entrenamiento-maraton-lesionado/'),
  ('https://triaperformance.com/blog/plan-entrenamiento-maraton-valencia/'),
  ('https://triaperformance.com/blog/preparacion-triatlon-larga-distancia-volumen/'),
  ('https://triaperformance.com/blog/problemas-estomacales-triatlon-calor/'),
  ('https://triaperformance.com/blog/regulacion-intensidad-umbral-tiempo-real/'),
  ('https://triaperformance.com/blog/rodilla-corredor-fuerza-excentrica/'),
  ('https://triaperformance.com/blog/rutina-activacion-pre-carrera/'),
  ('https://triaperformance.com/blog/stack-recuperacion-resistencia-creatina-sueno/'),
  ('https://triaperformance.com/blog/volumen-entrenamiento-triatlon-amateur-caso-estudio/'),
  ('https://triaperformance.com/blog/w-prime-potencia-ciclismo-calcular-fatiga/'),
  ('https://triaperformance.com/blog/zonas-potencia-stryd-umbral-lactato/'),
  ('https://triaperformance.com/en/blog/120g-carbohydrates-triathlon-amateur-strategy/'),
  ('https://triaperformance.com/en/blog/achilles-tendon-pain-running/'),
  ('https://triaperformance.com/en/blog/age-group-triathlon-training-load/'),
  ('https://triaperformance.com/en/blog/cycling-training-plan-weight-loss/'),
  ('https://triaperformance.com/en/blog/cycling-weight-loss-training-plan/'),
  ('https://triaperformance.com/en/blog/cycling-zone-2-fat-loss-plan/'),
  ('https://triaperformance.com/en/blog/endurance-recovery-stack-sleep-creatine/'),
  ('https://triaperformance.com/en/blog/first-marathon-training-volume/'),
  ('https://triaperformance.com/en/blog/ftp-vs-critical-power-cycling-zones/'),
  ('https://triaperformance.com/en/blog/half-to-full-distance-triathlon-transition/'),
  ('https://triaperformance.com/en/blog/heat-impact-triathlete-stomach-nutrition-strategies/'),
  ('https://triaperformance.com/en/blog/how-to-choose-a-marathon-plan/'),
  ('https://triaperformance.com/en/blog/how-to-program-hyrox-run-transitions-sled-fatigue/'),
  ('https://triaperformance.com/en/blog/hyrox-and-running-training-plan-weight-loss/'),
  ('https://triaperformance.com/en/blog/improve-threshold-running-without-wearables/'),
  ('https://triaperformance.com/en/blog/index/'),
  ('https://triaperformance.com/en/blog/intensity-control-threshold-intervals/'),
  ('https://triaperformance.com/en/blog/kettlebell-strength-training-runners/'),
  ('https://triaperformance.com/en/blog/lactate-free-power-threshold-training-stryd/'),
  ('https://triaperformance.com/en/blog/long-distance-triathlon-training-guide/'),
  ('https://triaperformance.com/en/blog/marathon-durability-avoiding-the-wall/'),
  ('https://triaperformance.com/en/blog/marathon-muscular-durability-training/'),
  ('https://triaperformance.com/en/blog/marathon-training-volume-injury-prevention/'),
  ('https://triaperformance.com/en/blog/pre-race-activation-routine/'),
  ('https://triaperformance.com/en/blog/running-plan-for-weight-loss/'),
  ('https://triaperformance.com/en/blog/simplified-norwegian-method-amateurs/'),
  ('https://triaperformance.com/en/blog/simplified-norwegian-method-threshold-training/'),
  ('https://triaperformance.com/en/blog/threshold-training-without-lactate-strips/'),
  ('https://triaperformance.com/en/blog/valencia-marathon-pacing-guide/'),
  ('https://triaperformance.com/en/blog/valencia-marathon-training-plan/'),
  ('https://triaperformance.com/en/blog/worldtour-cycling-tactics-busy-amateurs/'),
  ('https://triaperformance.com/en/blog/zone-2-running-for-weight-loss-plan/'),
  ('https://triaperformance.com/pt/blog/arte-da-ativacao-rotinas-pre-prova/'),
  ('https://triaperformance.com/pt/blog/carga-treino-amador-metricas-elite/'),
  ('https://triaperformance.com/pt/blog/ciclismo-treino-perda-peso-sustentavel/'),
  ('https://triaperformance.com/pt/blog/como-escolher-seu-plano-de-maratona/'),
  ('https://triaperformance.com/pt/blog/como-treinar-para-maratona-iniciante/'),
  ('https://triaperformance.com/pt/blog/controle-intensidade-series-limiar/'),
  ('https://triaperformance.com/pt/blog/correr-dor-tendao-aquiles/'),
  ('https://triaperformance.com/pt/blog/corrida-para-emagrecimento-alto-volume/'),
  ('https://triaperformance.com/pt/blog/durabilidade-maratona-evitar-muro/'),
  ('https://triaperformance.com/pt/blog/durabilidade-muscular-maratona-ritmo/'),
  ('https://triaperformance.com/pt/blog/forca-kettlebell-corredores/'),
  ('https://triaperformance.com/pt/blog/ftp-vs-potencia-critica-zonas-ciclismo/'),
  ('https://triaperformance.com/pt/blog/guia-pacing-maratona-valencia/'),
  ('https://triaperformance.com/pt/blog/guia-preparacao-triathlon-longa-distancia/'),
  ('https://triaperformance.com/pt/blog/impacto-calor-estomago-triatleta/'),
  ('https://triaperformance.com/pt/blog/index/'),
  ('https://triaperformance.com/pt/blog/metodo-noruegues-simplificado-limiar/'),
  ('https://triaperformance.com/pt/blog/metodo-noruegues-simplificado-rpe-lactato/'),
  ('https://triaperformance.com/pt/blog/planilha-treino-maratona-volume/'),
  ('https://triaperformance.com/pt/blog/plano-treinamento-maratona-valencia/'),
  ('https://triaperformance.com/pt/blog/programar-transicoes-corrida-hyrox-sleds/'),
  ('https://triaperformance.com/pt/blog/realidade-120g-carboidratos-triathlon-amadores/'),
  ('https://triaperformance.com/pt/blog/ritmo-treino-regenerativo-maratona/'),
  ('https://triaperformance.com/pt/blog/stack-recuperacao-endurance-sono-creatina/'),
  ('https://triaperformance.com/pt/blog/transicao-media-longa-distancia-triatlo/'),
  ('https://triaperformance.com/pt/blog/treinamento-hibrido-emagrecimento-corrida-hyrox/'),
  ('https://triaperformance.com/pt/blog/treinar-o-limiar-sem-tiras-de-lactato/'),
  ('https://triaperformance.com/pt/blog/treino-de-limiar-com-float-recovery-maratona/'),
  ('https://triaperformance.com/pt/blog/treino-potencia-corrida-stryd/')
)
SELECT p.url,
       COALESCE(SUM(g.impressions),0) AS impressions,
       COALESCE(SUM(g.clicks),0)      AS clicks,
       MIN(g.data_date)               AS first_seen,
       MAX(g.data_date)               AS last_seen
FROM published p
LEFT JOIN gsc_url_query g ON g.url = p.url AND g.search_type='web'
GROUP BY p.url
ORDER BY impressions ASC, p.url;