-- Generated by backfill_existing_customers.py -- review before running.
INSERT INTO subscriber_tokens (twenty_person_id, email, token, preferred_language, active)
VALUES
  ('15a44855-bc31-42b2-9cd5-d661be25d603', 'rongoni6@hotmail.com', 'p4bYzfekrfmxCXhn4qCj', 'SPANISH')
ON CONFLICT (token) DO NOTHING;
