#!/usr/bin/env bash
#
# Triaperformance website deploy — reference copy.
#
# Live copy lives at ~/.hermes/deploy-website.sh on the VPS and is called by the
# existing 6am cron job (knowledge-base sync + site deploy in one pass).
# This file in the repo is documentation/backup, not the live source of truth.
#
# What changed vs. the previous version: the site is now generated by Eleventy
# from site/ instead of being hand-written HTML in website/. The build runs here
# on the VPS, into a temp directory. Nothing is published unless the build
# actually succeeded and produced a real homepage — so a broken build leaves the
# live site exactly as it was instead of half-deploying over it.

set -euo pipefail

REPO="$HOME/.hermes/triaperformance-docs"
BUILD_DIR="$(mktemp -d /tmp/tp-build.XXXXXX)"
WEBROOT="/var/www/triaperformance"

cleanup() { rm -rf "$BUILD_DIR"; }
trap cleanup EXIT

echo "[$(date -Is)] pulling repo"
cd "$REPO"
git pull --ff-only

echo "[$(date -Is)] installing dependencies"
npm ci --omit=dev --no-audit --no-fund

echo "[$(date -Is)] building site"
npx @11ty/eleventy --output="$BUILD_DIR"

# ---- Guards. Publish only if the build produced a real site. ----------------
if [ ! -f "$BUILD_DIR/index.html" ]; then
  echo "[$(date -Is)] BUILD FAILED — no index.html produced. Live site untouched." >&2
  exit 1
fi

PAGE_COUNT=$(find "$BUILD_DIR" -name '*.html' | wc -l)
if [ "$PAGE_COUNT" -lt 1 ]; then
  echo "[$(date -Is)] BUILD SUSPECT — only $PAGE_COUNT pages. Live site untouched." >&2
  exit 1
fi

echo "[$(date -Is)] publishing $PAGE_COUNT pages to $WEBROOT"
rsync -a --delete "$BUILD_DIR"/ "$WEBROOT"/

echo "[$(date -Is)] deploy complete"
