#!/usr/bin/env bash
#
# Triaperformance website deploy — reference copy.
#
# Live copy lives at ~/.hermes/deploy-website.sh on the VPS and is called by the
# existing 6am cron job (knowledge-base sync + site deploy in one pass).
# This file in the repo is documentation/backup, not the live source of truth.
#
# What changed vs. the previous version: the site is now generated by Eleventy
# from site/ instead of being hand-written HTML in website/. The build runs here
# on the VPS, into a temp directory. Nothing is published unless the build
# actually succeeded and produced a real homepage — so a broken build leaves the
# live site exactly as it was instead of half-deploying over it.

set -euo pipefail

REPO="$HOME/.hermes/triaperformance-docs"
BUILD_DIR="$(mktemp -d /tmp/tp-build.XXXXXX)"
WEBROOT="/var/www/triaperformance"

# mktemp -d creates the directory as 0700. `rsync -a` preserves permissions and,
# with a trailing slash on the source, applies the source directory's mode to the
# destination too — which silently turned the webroot into 0700 root:root and made
# Caddy (running as the `caddy` user) return 403 on every request. Fixing it at the
# source rather than patching the webroot afterwards.
chmod 755 "$BUILD_DIR"

cleanup() { rm -rf "$BUILD_DIR"; }
trap cleanup EXIT

echo "[$(date -Is)] syncing repo to origin"
cd "$REPO"
# The VPS is a strict mirror of GitHub — it builds and deploys, it never authors.
# `git pull --ff-only` was used here first and broke the deploy the moment the repo
# had a local commit (a link-check result committed on the box), because a diverged
# branch can't fast-forward. fetch + reset --hard can't diverge and can't conflict.
#
# Consequence, on purpose: any local change inside this checkout is discarded on
# every deploy. Nothing should ever be authored here. Anything a job on this box
# generates (link-check results, build output) belongs outside the repo or in
# .gitignore — see data/plan_link_status.json.
git fetch origin
git reset --hard origin/main
git clean -fd

# Dependencies. Only reinstall when package-lock.json has actually changed —
# this runs daily from cron, and a nightly `npm ci` means a nightly dependency on
# the npm registry being reachable. With `set -e`, one transient network failure
# would kill both the site deploy and the knowledge-base sync this same job does.
#
# NOT --omit=dev: Eleventy is a devDependency (it's a build tool, it ships nothing
# to the browser), so --omit=dev skips the one package this script actually needs.
LOCK_HASH="$(md5sum package-lock.json | cut -d' ' -f1)"
STAMP="$REPO/node_modules/.deploy-lock-hash"
if [ ! -d node_modules ] || [ ! -f "$STAMP" ] || [ "$(cat "$STAMP")" != "$LOCK_HASH" ]; then
  echo "[$(date -Is)] dependencies changed — running npm ci"
  npm ci --no-audit --no-fund
  echo "$LOCK_HASH" > "$STAMP"
else
  echo "[$(date -Is)] dependencies unchanged — skipping npm ci"
fi

echo "[$(date -Is)] building site"
# If a link-check run has left durable results outside the repo, prefer them over
# the committed copy — the checkout itself is wiped on every deploy (see above).
if [ -f "$HOME/.hermes/plan_link_status.json" ]; then
  export PLAN_LINK_STATUS="$HOME/.hermes/plan_link_status.json"
  echo "[$(date -Is)] using link status from $PLAN_LINK_STATUS"
fi
npx @11ty/eleventy --output="$BUILD_DIR"

# ---- Guards. Publish only if the build produced a real site. ----------------
if [ ! -f "$BUILD_DIR/index.html" ]; then
  echo "[$(date -Is)] BUILD FAILED — no index.html produced. Live site untouched." >&2
  exit 1
fi

PAGE_COUNT=$(find "$BUILD_DIR" -name '*.html' | wc -l)
if [ "$PAGE_COUNT" -lt 1 ]; then
  echo "[$(date -Is)] BUILD SUSPECT — only $PAGE_COUNT pages. Live site untouched." >&2
  exit 1
fi

echo "[$(date -Is)] publishing $PAGE_COUNT pages to $WEBROOT"
rsync -a --delete "$BUILD_DIR"/ "$WEBROOT"/

# Belt and braces alongside the chmod on BUILD_DIR above: read for everyone,
# traverse (execute) on directories only. Harmless if already correct.
chmod -R a+rX "$WEBROOT"

# ---- Caddy config sync. Same "repo is truth" invariant as the site itself:
# the live /etc/caddy/Caddyfile should never be hand-edited, only ever written
# here from automation/Caddyfile. Validate the REPO's copy before touching
# anything live — a bad commit then just fails loudly here and leaves the
# running config alone, instead of reloading Caddy into a broken state.
echo "[$(date -Is)] checking Caddyfile for changes"
if ! cmp -s "$REPO/automation/Caddyfile" /etc/caddy/Caddyfile; then
  echo "[$(date -Is)] Caddyfile changed — validating before touching the live one"
  if sudo caddy validate --config "$REPO/automation/Caddyfile"; then
    sudo cp "$REPO/automation/Caddyfile" /etc/caddy/Caddyfile
    sudo systemctl reload caddy
    echo "[$(date -Is)] Caddyfile updated and reloaded"
  else
    echo "[$(date -Is)] CADDYFILE VALIDATION FAILED — live config left untouched, site deploy continues" >&2
  fi
else
  echo "[$(date -Is)] Caddyfile unchanged"
fi

# ---- Post-deploy verification. Test what a visitor actually gets, not just
# whether files exist — the 403 that motivated this was invisible to a file check.
echo "[$(date -Is)] verifying the live site responds"
# --resolve, not -H 'Host:'. Caddy routes TLS by SNI, and curl sends no SNI for a
# bare IP address, so https://127.0.0.1 with a Host header fails the handshake
# before HTTP is ever spoken — it reports 000 on a site that is working fine.
# --resolve keeps the real hostname (so SNI, Host and cert all match) while still
# connecting to the loopback address.
verify_failed=0
for path in "/" "/planes/running/" "/members/login/" "/blog/"; do
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 \
         --resolve "triaperformance.com:443:127.0.0.1" \
         "https://triaperformance.com${path}") || code="000"
  if [ "$code" = "200" ]; then
    echo "  OK   $code  $path"
  else
    echo "  FAIL $code  $path" >&2
    verify_failed=1
  fi
done
if [ "$verify_failed" = "1" ]; then
  echo "[$(date -Is)] WARNING: the site is deployed but not serving all paths correctly." >&2
fi

# Self-update. The live script lives at ~/.hermes/deploy-website.sh, separate from
# this file in the repo, so improvements to it would otherwise never reach the box —
# and a broken live script can't pull its own fix, which is exactly how the July 27
# diverged-branch failure became unrecoverable without manual intervention.
#
# Copied at the END, after a successful deploy, so a bad commit can't brick the
# deploy path: the new version only takes effect on the next run, and only if this
# run got all the way here. Deliberately not exec'ing the repo copy directly —
# bash reads scripts incrementally, so rewriting the running file mid-execution
# is its own class of bug.
LIVE="$HOME/.hermes/deploy-website.sh"
if ! cmp -s "$REPO/automation/deploy-website.sh" "$LIVE"; then
  cp "$REPO/automation/deploy-website.sh" "$LIVE"
  chmod +x "$LIVE"
  echo "[$(date -Is)] deploy script updated — new version takes effect next run"
fi

echo "[$(date -Is)] deploy complete"
