#!/usr/bin/env bash
#
# Triaperformance website deploy — reference copy.
#
# Live copy lives at ~/.hermes/deploy-website.sh on the VPS and is called by the
# existing 6am cron job (knowledge-base sync + site deploy in one pass).
# This file in the repo is documentation/backup, not the live source of truth.
#
# What changed vs. the previous version: the site is now generated by Eleventy
# from site/ instead of being hand-written HTML in website/. The build runs here
# on the VPS, into a temp directory. Nothing is published unless the build
# actually succeeded and produced a real homepage — so a broken build leaves the
# live site exactly as it was instead of half-deploying over it.

set -euo pipefail

REPO="$HOME/.hermes/triaperformance-docs"
BUILD_DIR="$(mktemp -d /tmp/tp-build.XXXXXX)"
WEBROOT="/var/www/triaperformance"

# mktemp -d creates the directory as 0700. `rsync -a` preserves permissions and,
# with a trailing slash on the source, applies the source directory's mode to the
# destination too — which silently turned the webroot into 0700 root:root and made
# Caddy (running as the `caddy` user) return 403 on every request. Fixing it at the
# source rather than patching the webroot afterwards.
chmod 755 "$BUILD_DIR"

cleanup() { rm -rf "$BUILD_DIR"; }
trap cleanup EXIT

echo "[$(date -Is)] syncing repo to origin"
cd "$REPO"
# The VPS is a strict mirror of GitHub — it builds and deploys, it never authors.
# `git pull --ff-only` was used here first and broke the deploy the moment the repo
# had a local commit (a link-check result committed on the box), because a diverged
# branch can't fast-forward. fetch + reset --hard can't diverge and can't conflict.
#
# Consequence, on purpose: any local change inside this checkout is discarded on
# every deploy. Nothing should ever be authored here. Anything a job on this box
# generates (link-check results, build output) belongs outside the repo or in
# .gitignore — see data/plan_link_status.json.
git fetch origin
git reset --hard origin/main
git clean -fd

# Dependencies. Only reinstall when package-lock.json has actually changed —
# this runs daily from cron, and a nightly `npm ci` means a nightly dependency on
# the npm registry being reachable. With `set -e`, one transient network failure
# would kill both the site deploy and the knowledge-base sync this same job does.
#
# NOT --omit=dev: Eleventy is a devDependency (it's a build tool, it ships nothing
# to the browser), so --omit=dev skips the one package this script actually needs.
LOCK_HASH="$(md5sum package-lock.json | cut -d' ' -f1)"
STAMP="$REPO/node_modules/.deploy-lock-hash"
if [ ! -d node_modules ] || [ ! -f "$STAMP" ] || [ "$(cat "$STAMP")" != "$LOCK_HASH" ]; then
  echo "[$(date -Is)] dependencies changed — running npm ci"
  npm ci --no-audit --no-fund
  echo "$LOCK_HASH" > "$STAMP"
else
  echo "[$(date -Is)] dependencies unchanged — skipping npm ci"
fi

echo "[$(date -Is)] building site"
# If a link-check run has left durable results outside the repo, prefer them over
# the committed copy — the checkout itself is wiped on every deploy (see above).
if [ -f "$HOME/.hermes/plan_link_status.json" ]; then
  export PLAN_LINK_STATUS="$HOME/.hermes/plan_link_status.json"
  echo "[$(date -Is)] using link status from $PLAN_LINK_STATUS"
fi
# Sequence board data (added September 6, 2026). Written BEFORE the build,
# because /admin/secuencias/ is a static page and this is its only source.
# The script never fails the deploy: if Postgres is unreachable it leaves the
# previous sequences.json in place and exits 0 -- a stale table beats no site,
# and the page prints `generated_at` so a stale one says so out loud.
python3 automation/build-sequences-data.py || true

npx @11ty/eleventy --output="$BUILD_DIR"

# ---- Guards. Publish only if the build produced a real site. ----------------
if [ ! -f "$BUILD_DIR/index.html" ]; then
  echo "[$(date -Is)] BUILD FAILED — no index.html produced. Live site untouched." >&2
  exit 1
fi

PAGE_COUNT=$(find "$BUILD_DIR" -name '*.html' | wc -l)
if [ "$PAGE_COUNT" -lt 1 ]; then
  echo "[$(date -Is)] BUILD SUSPECT — only $PAGE_COUNT pages. Live site untouched." >&2
  exit 1
fi

echo "[$(date -Is)] publishing $PAGE_COUNT pages to $WEBROOT"
rsync -a --delete "$BUILD_DIR"/ "$WEBROOT"/

# Belt and braces alongside the chmod on BUILD_DIR above: read for everyone,
# traverse (execute) on directories only. Harmless if already correct.
chmod -R a+rX "$WEBROOT"

# ---- Caddy config sync. Same "repo is truth" invariant as the site itself:
# the live /etc/caddy/Caddyfile should never be hand-edited, only ever written
# here from automation/Caddyfile. Validate the REPO's copy before touching
# anything live — a bad commit then just fails loudly here and leaves the
# running config alone, instead of reloading Caddy into a broken state.
echo "[$(date -Is)] checking Caddyfile for changes"
if ! cmp -s "$REPO/automation/Caddyfile" /etc/caddy/Caddyfile; then
  echo "[$(date -Is)] Caddyfile changed — validating before touching the live one"
  if sudo caddy validate --config "$REPO/automation/Caddyfile"; then
    sudo cp "$REPO/automation/Caddyfile" /etc/caddy/Caddyfile
    sudo systemctl reload caddy
    echo "[$(date -Is)] Caddyfile updated and reloaded"
  else
    echo "[$(date -Is)] CADDYFILE VALIDATION FAILED — live config left untouched, site deploy continues" >&2
  fi
else
  echo "[$(date -Is)] Caddyfile unchanged"
fi

# ---- Hermes config sync. Same "repo is truth" invariant as the site and the
# Caddyfile: ~/.hermes/config.yaml carried Hermes's model, allowlist and
# transcription settings and existed in no repo at all, so a rebuild lost them
# and no change to them was reviewable. Added September 4, 2026, after the
# second Gemini migration in three weeks re-paid the same manual edit.
#
# Validated against the REPO's copy before anything live is touched, exactly like
# the Caddyfile — a bad commit fails loudly here and leaves the running config
# alone. The validation is deliberately stronger than "does it parse": a
# truncated or half-written YAML can parse fine and still be missing the model
# block, and the failure mode of that is Hermes starting on a default nobody
# chose. So it asserts the model key survives the round trip.
#
# CONSEQUENCE, stated because it is a real trade and not a detail: the Hermes
# dashboard's config editor becomes a VIEW. Anything edited there is reverted on
# the next deploy. That is the same bargain already accepted for /etc/caddy/
# Caddyfile, and it is the point — a box-only config is what this closes.
HERMES_CFG="$HOME/.hermes/config.yaml"
REPO_CFG="$REPO/automation/hermes-config.yaml"
if [ -f "$REPO_CFG" ]; then
  if ! cmp -s "$REPO_CFG" "$HERMES_CFG"; then
    echo "[$(date -Is)] hermes config.yaml changed — validating the repo copy"
    if docker exec -i hermes-gateway python3 -c \
         "import yaml,sys; d=yaml.safe_load(sys.stdin); assert isinstance(d,dict), 'not a mapping'; assert d.get('model',{}).get('default'), 'model.default missing'" \
         < "$REPO_CFG"; then
      cp "$HERMES_CFG" "$HERMES_CFG.bak-$(date +%F-%H%M)"
      cp "$REPO_CFG" "$HERMES_CFG"
      docker restart hermes-gateway hermes-dashboard >/dev/null
      echo "[$(date -Is)] hermes config.yaml updated and containers restarted"
    else
      echo "[$(date -Is)] HERMES CONFIG VALIDATION FAILED — live config left untouched" >&2
    fi
  else
    echo "[$(date -Is)] hermes config.yaml unchanged"
  fi
fi

# ---- Hermes cron pin drift check. Deliberately NOT a sync: ~/.hermes/cron/
# jobs.json is written by the dashboard every time a job is created or edited,
# so tracking it would fight the UI daily for no benefit. What actually hurt was
# never the file being untracked — it was a pin going stale silently. An
# agent-mode job pinned to a model that is no longer the default FAILS CLOSED
# (Hermes skips it rather than running on a model it wasn't created against),
# which is the safe direction and also the invisible one: on August 24 that cost
# a Monday coaching check-in, announced as one line in Telegram among other
# traffic.
#
# So this reports rather than repairs. Read-only, and it cannot fail the deploy:
# an instrumentation step must not be able to kill the thing it measures.
echo "[$(date -Is)] checking Hermes cron pins against the model default"
docker exec -i hermes-gateway python3 - <<'PYCHECK' || echo "[$(date -Is)] pin check skipped (hermes not reachable)" >&2
import json, os, yaml
try:
    default = yaml.safe_load(open('/opt/data/config.yaml'))['model']['default']
    d = json.load(open('/opt/data/cron/jobs.json'))
    jobs = d if isinstance(d, list) else d.get('jobs', d)
    jobs = jobs if isinstance(jobs, list) else list(jobs.values())
except Exception as e:
    print("  pin check could not read config or jobs: %s" % e); raise SystemExit(0)
stale = 0
for j in jobs:
    # no_agent jobs run a script with no LLM call at all, so the drift guard
    # does not apply to them. They are immune, not merely unpinned.
    if j.get('no_agent'):
        print("  ok      %-42s no_agent (no model)" % j.get('name'))
        continue
    m = j.get('model')
    if not m:
        print("  WARN    %-42s UNPINNED -> runs on the global default" % j.get('name'))
        stale += 1
    elif m != default:
        print("  WARN    %-42s pinned %s, default is %s" % (j.get('name'), m, default))
        stale += 1
    else:
        print("  ok      %-42s %s" % (j.get('name'), m))
if stale:
    print("  %d job(s) will FAIL CLOSED and skip their next run until re-pinned." % stale)
PYCHECK

# ---- Post-deploy verification. Test what a visitor actually gets, not just
# whether files exist — the 403 that motivated this was invisible to a file check.
echo "[$(date -Is)] verifying the live site responds"
# --resolve, not -H 'Host:'. Caddy routes TLS by SNI, and curl sends no SNI for a
# bare IP address, so https://127.0.0.1 with a Host header fails the handshake
# before HTTP is ever spoken — it reports 000 on a site that is working fine.
# --resolve keeps the real hostname (so SNI, Host and cert all match) while still
# connecting to the loopback address.
verify_failed=0
# robots.txt and sitemap.xml added Aug 6, 2026 after Ahrefs reported robots.txt
# unreachable. Both were serving fine when checked, so the alert was most likely
# transient — a crawl landing inside the rsync window, when the webroot is being
# replaced. That is exactly the failure this loop exists to catch, and neither
# file was in it: they are passthrough assets, not pages, so a page-only check
# would never have noticed. They are also the two files whose absence silently
# costs indexing rather than producing a visible error.
# The three login paths are here for a specific reason (added Aug 10, 2026): they
# are the only pages under /members/ that Caddy serves WITHOUT the auth gate, via
# an explicit path list in @membersPublicPages. If that list ever drifts from what
# the build actually emits, the symptom is a locked-out subscriber, not an error
# anywhere — the page just redirects to itself. A 200 here is the cheap proof it
# still lines up. (The gated pages can't be checked this way; unauthenticated they
# correctly return a 302, which is a pass, not a failure.)
for path in "/" "/planes/running/" "/members/login/" "/members/en/login/" "/members/pt/login/" "/blog/" "/robots.txt" "/sitemap.xml"; do
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 \
         --resolve "triaperformance.com:443:127.0.0.1" \
         "https://triaperformance.com${path}") || code="000"
  if [ "$code" = "200" ]; then
    echo "  OK   $code  $path"
  else
    echo "  FAIL $code  $path" >&2
    verify_failed=1
  fi
done
if [ "$verify_failed" = "1" ]; then
  echo "[$(date -Is)] WARNING: the site is deployed but not serving all paths correctly." >&2
fi

# Self-update. The live script lives at ~/.hermes/deploy-website.sh, separate from
# this file in the repo, so improvements to it would otherwise never reach the box —
# and a broken live script can't pull its own fix, which is exactly how the July 27
# diverged-branch failure became unrecoverable without manual intervention.
#
# Copied at the END, after a successful deploy, so a bad commit can't brick the
# deploy path: the new version only takes effect on the next run, and only if this
# run got all the way here. Deliberately not exec'ing the repo copy directly —
# bash reads scripts incrementally, so rewriting the running file mid-execution
# is its own class of bug.
LIVE="$HOME/.hermes/deploy-website.sh"
if ! cmp -s "$REPO/automation/deploy-website.sh" "$LIVE"; then
  cp "$REPO/automation/deploy-website.sh" "$LIVE"
  chmod +x "$LIVE"
  echo "[$(date -Is)] deploy script updated — new version takes effect next run"
fi

echo "[$(date -Is)] deploy complete"
